name: Build Winlator APK

on:
  workflow_dispatch: # Allows you to run the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # This fixes the Node 20 warning
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Important if Winlator uses gladio/vortek submodules!
          
      - name: Set up JDK
        uses: actions/setup-java@v4 # <-- Update this from v3 to v4
        with:
          java-version: '17' # Winlator usually requires 17 or 11
          distribution: 'temurin'
          
      # Add this step if gradle fails with a permission error
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build with Gradle
        run: ./gradlew assembleRelease
